//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string sellerUsername { get; set; }
        public int categoryId { get; set; }
        public int productId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public double price { get; set; }
        public System.DateTime date { get; set; }
        public string condition { get; set; }
        public string status { get; set; }
    }
}
